### ISSUE TITLE
Reload Scene Fails due to LineShape3D Skipping Initialization

### ISSUE THREAD

**Issue by dagrooms52** [Firepal/godot-polyliner#4]
LinePath3D in a scene tree prevents the scene from being loaded and reloaded via script. 
This is due to `_draw()` being called before `_enter_tree()`, so the `_mesh_instance` is null in `_draw()`.
See this repo for a repro of the issue: https://github.com/dagrooms52/PolylinerReloadRepro

**Comment by Firepal** [comment]
Could reproduce.
I would rather not add a check inside `_draw()` or `_rd()` for `_mesh_instance` being initialized because I feel like someone might want to run it every frame, but it seems Godot doesn't really give me a choice here.

**Comment by Firepal** [comment]
Honestly, I don't really develop using Godot these days, so my understanding of how it initializes nodes in scenes is limited.
Even then, the documentation is limited too, and the community will generally ask you to look at the engine code. My brain is not (yet?) wired favorably for C++ syntax, hehe...

There's something strange with the reloading, the Curve3D state persists between reloads. 
When I add points to the Curve3D right after the reload call, it doesn't roll back to the initial state of the Curve3D as it was in the editor, and seemingly just keeps going with the same Curve3D of the last reload. At least, this is what I think is happening.

if you wanna see what that looks like, change the reload function to this
```gdscript
func _on_reload_pressed():
	get_tree().reload_current_scene()
	$"LinePath3D".curve.add_point(Vector3(randf(),randf(),randf()))
```

**Comment by Firepal** [comment]
I think that fix will suffice for now... I don't know what else I could do.
